### ISSUE TITLE
Some msgs are dropped

### ISSUE THREAD

**Issue by javijurado** [septentrio-gnss/septentrio_gnss_driver#103]
Hello,
I  bought asterxsbi3 pro and to read the data I use ros2 node. I saw that the topic twits_ins has a rate 100 Hz but checking some plot I saw some frames are dropped  As you can see in the picture attached, some msgs have dissapeared.

![missing_data](https://github.com/septentrio-gnss/septentrio_gnss_driver/assets/129072744/a96bab1a-e91c-43a0-9615-c42bd30f2961)
**twist_ins/linear/x** 

Any advise?

**Comment by thomasemter** [comment]
Hi there,

I am not sure what that plot is showing exactly, since on the x-axis there seems to be a 1e10 scaling? Can you please explain what shown and if this is live data or from a bag file? Which tool did you use to visualize or record the data? Some ROS 2 tools are known to have problems with high rate data, e.g. [here](https://answers.ros.org/question/396188/node-publishes-only-half-of-expected-frequency/). Also, unreliable connections may have [side effects](https://discourse.ros.org/t/ros2-qos-reliability-issue/31700).

Also, which interface of the Asterx is used? Serial baud rates have to be set appropriately for high rate data.

**Comment by javijurado** [comment]
Sorry for my bad explanation.
Few days ago, we were using the AsteRx SBi3 Pro to get the position and ins velocity on the platform. After analyze the data, we saw some messages are dropped. You can see on the picture attached below.

![image](https://github.com/septentrio-gnss/septentrio_gnss_driver/assets/129072744/bf785820-75da-4105-9143-8ca8454746b0)

We though that the problem was the software that we were using to plot the data. We have tried plotjuggler, Floxglove and our own script to plot data (On real time and using rosbags ). Same result in each plotter. 

We are using ethernet interface to get the data.

**Comment by thomasemter** [comment]
Thank you for the clarification. I assume you are running the driver with ROS timestamps, i.e. `use_gnss_time` set to `false`, correct?

Counting the data points in your foxglove screenshot, there are 20 withing 0.2 s, which is 100 Hz data rate. So it seems you are not loosing data but the rate ist fluctuating. This could be caused by a highly loaded network. Are there other devices in your network like GigE cameras or LiDARs producing a lot of UDP traffic? Running `ros2 topic hz twist_ins` gives you some statistics on the delta times. Can you try to run this with just the AsteRx connected and no other active ROS nodes?

**Comment by thomasemter** [comment]
I am sorry but in that case I am a little clueless right now. Some jitter of a few % is normal but I haven't experienced it to that extent. Are you using TCP and could you try with UDP for comparison (parameter `stream_device. udp`)?

**Comment by javijurado** [comment]
My actual configuration is this one:
```

# Configuration Settings for the Rover Rx

# GNSS/INS Parameters

device: tcp://my_ip:28784 

serial:
  baudrate: 921600
  hw_flow_control: "off"

# stream_device:
#   tcp:
#     ip_server: ""
#     port: 0
#   udp:
#     ip_server: ""
#     port: 0
#     unicast_ip: ""

configure_rx: true

# login:
#   user: ""
#   password: ""

# osnma:
#   mode: "off"
#   ntp_server: ""
#   keep_open: true

frame_id: gnss 

imu_frame_id: imu

poi_frame_id: base_link

vsm_frame_id: vsm

aux1_frame_id: aux1

vehicle_frame_id: base_link

local_frame_id: odom

insert_local_frame: false

get_spatial_config_from_tf: false 

lock_utm_zone: true

use_ros_axis_orientation: true

receiver_type: ins

multi_antenna: true

datum: Default

# poi_to_arp: # offsets of the main GNSS antenna reference point (ARP) with respect to the point of interest (POI = marker). Use for static receivers only.
#   delta_e: 0.0
#   delta_n: 0.0
#   delta_u: 0.0

att_offset: ## for board setup
  heading: 90.0
  pitch: 0.0

ant_type: "SEPPOLANT_MC.V2"
ant_serial_nr: "Unknown"
ant_aux1_type: "SEPPOLANT_MC.V2"
ant_aux1_serial_nr: "Unknown"

polling_period: ## tbd what it can do/ we need
  pvt: 0
  rest: 500

use_gnss_time: false

latency_compensation: false

#Data hidden
#rtk_settings:
  # ip_server_1:
  #   id: ""
  #   port: 0
  #   rtk_standard: "auto"
  #   send_gga: "auto"
  #   keep_open: true
  # serial_1:
  #   port: ""
  #   baud_rate: 115200
  #   rtk_standard: "auto"
  #   send_gga: "auto"
  #   keep_open: true

publish:
  # For both GNSS and INS Rxs
  navsatfix: true
  gpsfix: true
  gpgga: true
  gprmc: true
  gpst: true
  measepoch: false
  pvtcartesian: true
  pvtgeodetic: true
  basevectorcart: false
  basevectorgeod: false
  poscovcartesian: true
  poscovgeodetic: true
  velcovcartesian: false
  velcovgeodetic: true
  atteuler: true
  attcoveuler: true
  pose: true
  twist: true
  diagnostics: true
  aimplusstatus: true
  galauthstatus: false
  # For GNSS Rx only
  gpgsa: false
  gpgsv: false
  # For INS Rx only
  insnavcart: true
  insnavgeod: true
  extsensormeas: false
  imusetup: false
  velsensorsetup: false
  exteventinsnavcart: false
  exteventinsnavgeod: false
  imu: true
  localization: true
  tf: false
  localization_ecef: false
  tf_ecef: false

# INS-Specific Parameters

ins_spatial_config:
  imu_orientation:
    theta_x: 180
    theta_y: 0.0
    theta_z: 0.0
  poi_lever_arm:
    delta_x: 0.0
    delta_y: 0.0
    delta_z: 0.0
  ant_lever_arm: 
    x: 0.0
    y: -0.305
    z: -0.0102
  vsm_lever_arm:
    vsm_x: 0.0
    vsm_y: 0.0
    vsm_z: 0.0

ins_initial_heading: auto

ins_std_dev_mask:
  att_std_dev: 5.0
  pos_std_dev: 10.0

ins_use_poi: false

ins_vsm:
  ros:
    source: "twist"
    config: [true, true, false]
    variances_by_parameter: false
    # variances: [0.0, 0.0, 0.0]
  # ip_server:
  #   id: ""
  #   port: 0
  #   keep_open: true
  # serial:
  #   port: ""
  #   baud_rate: 115200
  #   keep_open: true

# logger

activate_debug_log: false
```

**Comment by abaeyens-imod** [comment]
thank you @thomasemter for looking into this.

Unfortunately, we're still experiencing issues. Sometimes it works very well, with ROS messages on topic `twist_ins` being timestamped and arriving at a steady 100 Hz (<5 ms in TCP and < 2 ms UDP), while at other times we see an interval on the order of 100 ms between subsequent messages and UDP mode not even working.

Today we tested with several devices. All the tried configurations reproduced the same undesired result of having a gap of at least 20 ms somewhere in every subsequent 100 messages.

We tried two routers, two network switches, two different laptops with a different OS version (Ubuntu 20.04 and 22.04) and ROS distributions (Foxy and Humble), four ways of connecting to the router (native gigabit port, two different USB-to-ethernet adapters and wifi). Internet access was disabled on the router side, the CPU load on the computer was negligible (< 10 %) and only two devices were connected to the router's switch (the Septentrio and our computer running ROS).

Capturing the TCP traffic with Wireshark showed that now and then there's a long delay - e.g. 80 ms - between subsequent TCP packets.

Enabling UDP mode caused UDP packages to show up in Wireshark, however the Septentrio node didn't publish any messages on the `twist_ins` topic. It did max out one CPU core though. This did work in the past.

I assume we're making some error in a configuration somewhere, however it is unclear to me where. We would greatly appreciate any suggestions on how to resolve this. In case there is a need for more information from our side, please let know.

---

Further information: The receiver firmware is 1.4.1 and for the ROS node we run the latest version from GitHub compiled from source. We launched the Septentrio node using `ros2 launch septentrio_gnss_driver rover.launch.py`.
This is the modified `rover.yaml` config file we used for TCP:
```
# Configuration Settings for the Rover Rx

# GNSS/INS Parameters

device: tcp://192.168.140.80:28784

configure_rx: true

login:
  user: ""
  password: ""  

osnma:
  mode: "off"
  ntp_server: ""
  keep_open: true

frame_id: gnss

imu_frame_id: imu

poi_frame_id: base_link

vsm_frame_id: vsm

aux1_frame_id: aux1

vehicle_frame_id: base_link

local_frame_id: odom

insert_local_frame: false

get_spatial_config_from_tf: false

lock_utm_zone: true

use_ros_axis_orientation: true

receiver_type: ins

multi_antenna: true

datum: Default

poi_to_arp:
  delta_e: 0.0
  delta_n: 0.0
  delta_u: 0.0

att_offset:
  heading: 0.0
  pitch: 0.0

ant_type: "SEPPOLANT_MC.V2"
ant_serial_nr: "Unknown"
ant_aux1_type: "SEPPOLANT_MC.V2"
ant_aux1_serial_nr: "Unknown"

polling_period:
  pvt: 0
  rest: 500

use_gnss_time: false

latency_compensation: false

rtk_settings:
  ntrip_1:
    id: ""
    caster: ""
    caster_port: 2101
    username: ""
    password: ""
    mountpoint: ""
    version: "v2"
    tls: false
    fingerprint: ""
    rtk_standard: "auto"
    send_gga: "auto"
    keep_open: true
  ip_server_1:
    id: ""
    port: 0
    rtk_standard: "auto"
    send_gga: "auto"
    keep_open: true
  serial_1:
    port: ""
    baud_rate: 115200
    rtk_standard: "auto"
    send_gga: "auto"
    keep_open: true

publish:
  # For both GNSS and INS Rxs
  navsatfix: false
  gpsfix: true
  gpgga: false
  gprmc: false
  gpst: false
  measepoch: false
  pvtcartesian: false
  pvtgeodetic: true
  basevectorcart: false
  basevectorgeod: false
  poscovcartesian: false
  poscovgeodetic: true
  velcovcartesian: false
  velcovgeodetic: true
  atteuler: true
  attcoveuler: true
  pose: false
  twist: true
  diagnostics: false
  aimplusstatus: true
  galauthstatus: false
  # For GNSS Rx only
  gpgsa: false
  gpgsv: false
  # For INS Rx only
  insnavcart: false
  insnavgeod: false
  extsensormeas: false
  imusetup: false
  velsensorsetup: false
  exteventinsnavcart: false
  exteventinsnavgeod: false
  imu: false
  localization: false
  tf: false
  localization_ecef: false
  tf_ecef: false


# INS-Specific Parameters

ins_spatial_config:
  imu_orientation:
    theta_x: 0.0
    theta_y: 0.0
    theta_z: 0.0
  poi_lever_arm:
    delta_x: 1.0
    delta_y: 0.0
    delta_z: 0.0
  ant_lever_arm:
    x: 1.0
    y: 0.0
    z: 0.0
  vsm_lever_arm:
    vsm_x: 1.0
    vsm_y: 0.0
    vsm_z: 0.0

ins_initial_heading: auto

ins_std_dev_mask:
  att_std_dev: 5.0
  pos_std_dev: 10.0

ins_use_poi: false

ins_vsm:
  ros:
    source: ""
    config: [false, false, false]
    variances_by_parameter: false
    variances: [0.0, 0.0, 0.0]
  ip_server:
    id: ""
    port: 0
    keep_open: true
  serial:
    port: ""
    baud_rate: 115200
    keep_open: true


# logger

activate_debug_log: false
```

For using UDP, we added the following below `device`:
```
stream_device:
  udp:
    ip_server: "IPS1"
    port: 28785
    unicast_ip: "192.168.140.100"
```
